name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: [oldstable, stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Xvfb and xclip
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y xvfb xclip
          sudo Xvfb :99 -ac -screen 0 1024x768x8 &
          export DISPLAY=:99
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v -race ./...
      - name: Integration test scripts (macOS)
        if: matrix.os == 'macos-latest'
        run: ./scripts/test_macos.sh
      - name: Integration test scripts (Windows)
        if: matrix.os == 'windows-latest'
        run: .\scripts\test_windows.ps1
      - name: Integration test scripts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: ./scripts/test_linux.sh